# Generated by Django 3.1.3 on 2020-12-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20201215_0302'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surveys',
            field=models.ManyToManyField(to='basic_app.Survey'),
        ),
    ]
