# Generated by Django 3.1.3 on 2020-12-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20201215_0409'),
        ('accounts', '0002_userprofile_surveys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='surveys',
            field=models.ManyToManyField(blank=True, to='basic_app.Survey'),
        ),
    ]
