# Generated by Django 3.1.3 on 2020-12-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='surveys',
        ),
    ]
