# Generated by Django 3.1.3 on 2020-12-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('basic_app', '0003_remove_userprofile_surveys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
