# Generated by Django 3.1.3 on 2020-12-14 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tags',
        ),
        migrations.AddField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(to='basic_app.Tag'),
        ),
    ]
