# Generated by Django 3.1.3 on 2020-12-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20201215_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic_app.Tag'),
        ),
    ]
